import type { ChartType, TrendPolarity } from "~/types/metrics";
import type { CountryCode } from "~/config/countries";

export interface MetricDefinition {
  id: string;
  name: string;
  unit: string;
  source: string;
  frequency: string;
  chartType: ChartType;
  description: string;
  section: string;
  trendPolarity: TrendPolarity;
  decimals: number;
  // Regression window (number of data points) and minimum slope threshold.
  // Arrow shows neutral if |slope| < trendThreshold — i.e. the series is flat.
  trendWindow: number;
  trendThreshold: number;
}

const auMetricDefinitions: MetricDefinition[] = [
  {
    id: "gdp",
    name: "GDP Growth",
    unit: "% YoY",
    source: "ABS",
    frequency: "Quarterly",
    chartType: "bar",
    description: "Annual gross domestic product growth rate",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,       // 4 quarters = 1 year
    trendThreshold: 0.05, // 0.05pp/quarter slope to register
  },
  {
    id: "gdp-per-capita",
    name: "GDP per Capita",
    unit: "% YoY",
    source: "ABS",
    frequency: "Quarterly",
    chartType: "bar",
    description: "Annual GDP per capita growth rate — adjusts for population growth",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,       // 4 quarters = 1 year
    trendThreshold: 0.05,
  },
  {
    id: "cpi",
    name: "Inflation (CPI)",
    unit: "% YoY",
    source: "ABS",
    frequency: "Monthly",
    chartType: "line",
    description: "Consumer Price Index — annual change",
    section: "Prices & Wages",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.05,
  },
  {
    id: "unemployment",
    name: "Unemployment",
    unit: "%",
    source: "ABS",
    frequency: "Monthly",
    chartType: "area",
    description: "Unemployment rate as % of labour force",
    section: "Labour Market",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.02,
  },
  {
    id: "cash-rate",
    name: "Cash Rate",
    unit: "%",
    source: "RBA",
    frequency: "~8x/year",
    chartType: "step",
    description: "RBA official cash rate target",
    section: "Financial & Monetary",
    trendPolarity: "neutral",
    decimals: 2,
    trendWindow: 4,       // last 4 decisions
    trendThreshold: 0.05,
  },
  {
    id: "wages",
    name: "Wage Growth",
    unit: "% YoY",
    source: "ABS",
    frequency: "Quarterly",
    chartType: "line",
    description: "Wage Price Index — annual change",
    section: "Prices & Wages",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "real-wages",
    name: "Real Wage Growth",
    unit: "% YoY",
    source: "ABS",
    frequency: "Quarterly",
    chartType: "line",
    description: "Wage growth minus inflation — change in purchasing power",
    section: "Prices & Wages",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "aud-usd",
    name: "AUD/USD",
    unit: "USD",
    source: "RBA",
    frequency: "Monthly",
    chartType: "area",
    description: "Australian dollar vs US dollar exchange rate",
    section: "External & Trade",
    trendPolarity: "neutral",
    decimals: 4,
    trendWindow: 6,
    trendThreshold: 0.002, // ~0.2 cent/month slope to register
  },
  {
    id: "trade",
    name: "Trade Balance",
    unit: "A$B",
    source: "ABS",
    frequency: "Monthly",
    chartType: "bar",
    description: "Goods trade balance (surplus/deficit)",
    section: "External & Trade",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.1,  // A$100M/month slope to register
  },
  {
    id: "underemployment",
    name: "Underemployment",
    unit: "%",
    source: "ABS",
    frequency: "Monthly",
    chartType: "area",
    description: "Share of employed people who want more work hours",
    section: "Labour Market",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.02,
  },
  {
    id: "household-spending",
    name: "Household Spending",
    unit: "% YoY",
    source: "ABS",
    frequency: "Monthly",
    chartType: "area",
    description: "Annual change in household consumer spending",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.1,
  },
  {
    id: "job-vacancies",
    name: "Job Vacancies",
    unit: "k",
    source: "ABS",
    frequency: "Quarterly",
    chartType: "bar",
    description: "Number of unfilled job vacancies (thousands)",
    section: "Labour Market",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 5,    // 5k/quarter slope to register
  },
  {
    id: "building-approvals",
    name: "Building Approvals",
    unit: "k dwellings",
    source: "ABS",
    frequency: "Monthly",
    chartType: "bar",
    description: "New residential dwelling units approved per month (thousands)",
    section: "Housing",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.3,  // 300 dwellings/month slope to register
  },
  {
    id: "dwelling-completions",
    name: "Dwelling Completions",
    unit: "k dwellings",
    source: "ABS",
    frequency: "Quarterly",
    chartType: "bar",
    description: "New residential dwellings completed per month (quarterly data normalised to monthly rate)",
    section: "Housing",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.2,  // ~200 dwellings/month slope to register
  },
  {
    id: "fiscal-balance",
    name: "Fiscal Balance",
    unit: "A$B",
    source: "ABS",
    frequency: "Quarterly",
    chartType: "bar",
    description: "General government net operating balance — trailing 12-month sum (surplus/deficit)",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 5,    // A$5B/quarter slope to register
  },
];

const nzMetricDefinitions: MetricDefinition[] = [
  {
    id: "gdp",
    name: "GDP Growth",
    unit: "% YoY",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "bar",
    description: "Annual gross domestic product growth rate",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "cpi",
    name: "Inflation (CPI)",
    unit: "% YoY",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "line",
    description: "Consumer Price Index — annual change",
    section: "Prices & Wages",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "unemployment",
    name: "Unemployment",
    unit: "%",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "area",
    description: "Unemployment rate as % of labour force",
    section: "Labour Market",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.02,
  },
  {
    id: "cash-rate",
    name: "Official Cash Rate",
    unit: "%",
    source: "FRED",
    frequency: "Monthly",
    chartType: "step",
    description: "RBNZ official cash rate (3-month interbank proxy)",
    section: "Financial & Monetary",
    trendPolarity: "neutral",
    decimals: 2,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "wages",
    name: "Wage Growth",
    unit: "% YoY",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "line",
    description: "Manufacturing hourly earnings — annual change",
    section: "Prices & Wages",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "real-wages",
    name: "Real Wage Growth",
    unit: "% YoY",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "line",
    description: "Wage growth minus inflation — change in purchasing power",
    section: "Prices & Wages",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "nzd-usd",
    name: "NZD/USD",
    unit: "USD",
    source: "FRED",
    frequency: "Monthly",
    chartType: "area",
    description: "New Zealand dollar vs US dollar exchange rate",
    section: "External & Trade",
    trendPolarity: "neutral",
    decimals: 4,
    trendWindow: 6,
    trendThreshold: 0.002,
  },
  {
    id: "trade",
    name: "Trade Balance",
    unit: "NZ$B",
    source: "FRED",
    frequency: "Monthly",
    chartType: "bar",
    description: "Goods trade balance (surplus/deficit)",
    section: "External & Trade",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.05,
  },
  {
    id: "retail-trade",
    name: "Retail Trade",
    unit: "% YoY",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "area",
    description: "Annual change in retail trade volume",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.1,
  },
  {
    id: "fiscal-balance",
    name: "Fiscal Balance (OBEGAL)",
    unit: "NZ$B",
    source: "NZ Treasury",
    frequency: "Annual",
    chartType: "bar",
    description: "Operating balance excluding gains and losses",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 1,
  },
];

const usMetricDefinitions: MetricDefinition[] = [
  {
    id: "gdp",
    name: "GDP Growth",
    unit: "% YoY",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "bar",
    description: "Real gross domestic product growth rate (annualised)",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "gdp-per-capita",
    name: "GDP per Capita",
    unit: "% YoY",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "bar",
    description: "Real GDP per capita growth rate — adjusts for population growth",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "personal-consumption",
    name: "Personal Consumption",
    unit: "% YoY",
    source: "FRED",
    frequency: "Monthly",
    chartType: "area",
    description: "Annual change in real personal consumption expenditures",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.1,
  },
  {
    id: "fiscal-balance",
    name: "Federal Surplus/Deficit",
    unit: "$B",
    source: "FRED",
    frequency: "Monthly",
    chartType: "bar",
    description: "Federal government monthly surplus or deficit — trailing 12-month sum",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 0,
    trendWindow: 6,
    trendThreshold: 20,
  },
  {
    id: "cpi",
    name: "Inflation (CPI)",
    unit: "% YoY",
    source: "FRED",
    frequency: "Monthly",
    chartType: "line",
    description: "Consumer Price Index — annual change",
    section: "Prices & Wages",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.05,
  },
  {
    id: "wages",
    name: "Wage Growth",
    unit: "% YoY",
    source: "FRED",
    frequency: "Monthly",
    chartType: "line",
    description: "Average hourly earnings — annual change",
    section: "Prices & Wages",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.05,
  },
  {
    id: "real-wages",
    name: "Real Wage Growth",
    unit: "% YoY",
    source: "FRED",
    frequency: "Monthly",
    chartType: "line",
    description: "Wage growth minus inflation — change in purchasing power",
    section: "Prices & Wages",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.05,
  },
  {
    id: "unemployment",
    name: "Unemployment",
    unit: "%",
    source: "FRED",
    frequency: "Monthly",
    chartType: "area",
    description: "Unemployment rate as % of labour force",
    section: "Labour Market",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.02,
  },
  {
    id: "underemployment",
    name: "Underemployment (U-6)",
    unit: "%",
    source: "FRED",
    frequency: "Monthly",
    chartType: "area",
    description: "Total unemployed plus marginally attached plus employed part-time for economic reasons",
    section: "Labour Market",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.02,
  },
  {
    id: "job-openings",
    name: "Job Openings",
    unit: "k",
    source: "FRED",
    frequency: "Monthly",
    chartType: "bar",
    description: "JOLTS total nonfarm job openings (thousands)",
    section: "Labour Market",
    trendPolarity: "positive",
    decimals: 0,
    trendWindow: 6,
    trendThreshold: 100,
  },
  {
    id: "fed-funds-rate",
    name: "Federal Funds Rate",
    unit: "%",
    source: "FRED",
    frequency: "~8x/year",
    chartType: "step",
    description: "Federal Reserve target rate — effective monthly average",
    section: "Financial & Monetary",
    trendPolarity: "neutral",
    decimals: 2,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "usd-index",
    name: "USD Index",
    unit: "index",
    source: "FRED",
    frequency: "Monthly",
    chartType: "area",
    description: "Trade-weighted broad US dollar index",
    section: "External & Trade",
    trendPolarity: "neutral",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.5,
  },
  {
    id: "trade",
    name: "Trade Balance",
    unit: "$B",
    source: "FRED",
    frequency: "Monthly",
    chartType: "bar",
    description: "Goods and services trade balance (surplus/deficit)",
    section: "External & Trade",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 2,
  },
  {
    id: "building-permits",
    name: "Building Permits",
    unit: "k",
    source: "FRED",
    frequency: "Monthly",
    chartType: "bar",
    description: "New privately-owned housing units authorised (thousands, SAAR)",
    section: "Housing",
    trendPolarity: "positive",
    decimals: 0,
    trendWindow: 6,
    trendThreshold: 20,
  },
  {
    id: "housing-starts",
    name: "Housing Starts",
    unit: "k",
    source: "FRED",
    frequency: "Monthly",
    chartType: "bar",
    description: "New privately-owned housing units started (thousands, SAAR)",
    section: "Housing",
    trendPolarity: "positive",
    decimals: 0,
    trendWindow: 6,
    trendThreshold: 20,
  },
];

const ukMetricDefinitions: MetricDefinition[] = [
  {
    id: "gdp",
    name: "GDP Growth",
    unit: "% YoY",
    source: "ONS",
    frequency: "Quarterly",
    chartType: "bar",
    description: "Annual gross domestic product growth rate",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "gdp-per-capita",
    name: "GDP per Capita",
    unit: "% YoY",
    source: "ONS",
    frequency: "Quarterly",
    chartType: "bar",
    description: "Annual GDP per capita growth rate — adjusts for population growth",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "retail-sales",
    name: "Retail Sales",
    unit: "% YoY",
    source: "ONS",
    frequency: "Monthly",
    chartType: "area",
    description: "Annual change in retail sales volume (quantity bought)",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.1,
  },
  {
    id: "cpi",
    name: "Inflation (CPI)",
    unit: "% YoY",
    source: "ONS",
    frequency: "Monthly",
    chartType: "line",
    description: "Consumer Price Index — annual change",
    section: "Prices & Wages",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.05,
  },
  {
    id: "wages",
    name: "Wage Growth (AWE)",
    unit: "% YoY",
    source: "ONS",
    frequency: "Monthly",
    chartType: "line",
    description: "Average weekly earnings — annual change (3-month average)",
    section: "Prices & Wages",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.05,
  },
  {
    id: "real-wages",
    name: "Real Wage Growth",
    unit: "% YoY",
    source: "ONS",
    frequency: "Monthly",
    chartType: "line",
    description: "Wage growth minus inflation — change in purchasing power",
    section: "Prices & Wages",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.05,
  },
  {
    id: "unemployment",
    name: "Unemployment",
    unit: "%",
    source: "ONS",
    frequency: "Monthly",
    chartType: "area",
    description: "Unemployment rate as % of labour force (3-month average)",
    section: "Labour Market",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.02,
  },
  {
    id: "economic-inactivity",
    name: "Economic Inactivity",
    unit: "%",
    source: "ONS",
    frequency: "Monthly",
    chartType: "area",
    description: "Share of working-age population not in the labour force (3-month average)",
    section: "Labour Market",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.02,
  },
  {
    id: "job-vacancies",
    name: "Job Vacancies",
    unit: "k",
    source: "ONS",
    frequency: "Monthly",
    chartType: "bar",
    description: "Number of unfilled job vacancies (thousands, 3-month average)",
    section: "Labour Market",
    trendPolarity: "positive",
    decimals: 0,
    trendWindow: 6,
    trendThreshold: 10,
  },
  {
    id: "bank-rate",
    name: "Bank Rate",
    unit: "%",
    source: "BoE",
    frequency: "~8x/year",
    chartType: "step",
    description: "Bank of England official interest rate",
    section: "Financial & Monetary",
    trendPolarity: "neutral",
    decimals: 2,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "gbp-usd",
    name: "GBP/USD",
    unit: "USD",
    source: "BoE",
    frequency: "Monthly",
    chartType: "area",
    description: "British pound vs US dollar exchange rate",
    section: "External & Trade",
    trendPolarity: "neutral",
    decimals: 4,
    trendWindow: 6,
    trendThreshold: 0.005,
  },
  {
    id: "trade",
    name: "Trade Balance",
    unit: "£B",
    source: "ONS",
    frequency: "Monthly",
    chartType: "bar",
    description: "Goods trade balance (surplus/deficit)",
    section: "External & Trade",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.5,
  },
];

const caMetricDefinitions: MetricDefinition[] = [
  {
    id: "gdp",
    name: "GDP Growth",
    unit: "% YoY",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "bar",
    description: "Annual gross domestic product growth rate",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "retail-sales",
    name: "Retail Sales",
    unit: "% YoY",
    source: "FRED",
    frequency: "Monthly",
    chartType: "area",
    description: "Annual change in retail trade volume",
    section: "Growth & Output",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.1,
  },
  {
    id: "cpi",
    name: "Inflation (CPI)",
    unit: "% YoY",
    source: "FRED",
    frequency: "Monthly",
    chartType: "line",
    description: "Consumer Price Index — annual change",
    section: "Prices & Wages",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.05,
  },
  {
    id: "wages",
    name: "Wage Growth",
    unit: "% YoY",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "line",
    description: "Manufacturing hourly earnings — annual change",
    section: "Prices & Wages",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "real-wages",
    name: "Real Wage Growth",
    unit: "% YoY",
    source: "FRED",
    frequency: "Quarterly",
    chartType: "line",
    description: "Wage growth minus inflation — change in purchasing power",
    section: "Prices & Wages",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "unemployment",
    name: "Unemployment",
    unit: "%",
    source: "FRED",
    frequency: "Monthly",
    chartType: "area",
    description: "Unemployment rate as % of labour force",
    section: "Labour Market",
    trendPolarity: "negative",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.02,
  },
  {
    id: "policy-rate",
    name: "Policy Rate",
    unit: "%",
    source: "FRED",
    frequency: "Monthly",
    chartType: "step",
    description: "Bank of Canada policy interest rate (3-month interbank proxy)",
    section: "Financial & Monetary",
    trendPolarity: "neutral",
    decimals: 2,
    trendWindow: 4,
    trendThreshold: 0.05,
  },
  {
    id: "cad-usd",
    name: "CAD/USD",
    unit: "USD",
    source: "FRED",
    frequency: "Monthly",
    chartType: "area",
    description: "Canadian dollar vs US dollar exchange rate",
    section: "External & Trade",
    trendPolarity: "neutral",
    decimals: 4,
    trendWindow: 6,
    trendThreshold: 0.002,
  },
  {
    id: "trade",
    name: "Trade Balance",
    unit: "C$B",
    source: "FRED",
    frequency: "Monthly",
    chartType: "bar",
    description: "Goods trade balance (surplus/deficit)",
    section: "External & Trade",
    trendPolarity: "positive",
    decimals: 1,
    trendWindow: 6,
    trendThreshold: 0.5,
  },
];

const allMetricDefinitions: Record<CountryCode, MetricDefinition[]> = {
  au: auMetricDefinitions,
  nz: nzMetricDefinitions,
  us: usMetricDefinitions,
  uk: ukMetricDefinitions,
  ca: caMetricDefinitions,
};

const allHeroMetricIds: Record<CountryCode, string[]> = {
  au: ["gdp", "cpi", "unemployment", "cash-rate"],
  nz: ["gdp", "cpi", "unemployment", "cash-rate"],
  us: ["gdp", "cpi", "unemployment", "fed-funds-rate"],
  uk: ["gdp", "cpi", "unemployment", "bank-rate"],
  ca: ["gdp", "cpi", "unemployment", "policy-rate"],
};

const allDashboardSections: Record<CountryCode, string[]> = {
  au: [
    "Growth & Output",
    "Prices & Wages",
    "Labour Market",
    "Financial & Monetary",
    "External & Trade",
    "Housing",
  ],
  nz: [
    "Growth & Output",
    "Prices & Wages",
    "Labour Market",
    "Financial & Monetary",
    "External & Trade",
  ],
  us: [
    "Growth & Output",
    "Prices & Wages",
    "Labour Market",
    "Financial & Monetary",
    "External & Trade",
    "Housing",
  ],
  uk: [
    "Growth & Output",
    "Prices & Wages",
    "Labour Market",
    "Financial & Monetary",
    "External & Trade",
  ],
  ca: [
    "Growth & Output",
    "Prices & Wages",
    "Labour Market",
    "Financial & Monetary",
    "External & Trade",
  ],
};

export function getMetricDefinitions(country: CountryCode): MetricDefinition[] {
  return allMetricDefinitions[country];
}

export function getHeroMetricIds(country: CountryCode): string[] {
  return allHeroMetricIds[country];
}

export function getDashboardSections(country: CountryCode): string[] {
  return allDashboardSections[country];
}
